export const autoGeneratedWarningMessage = `/**
 * This file was automatically generated, PLEASE DO NOT MODIFY IT BY HAND.
 */`;

export function formatGeneratedFileExport(fileName: string) {
  return `export * from './${fileName}';\n`;
}

export function formatInterfaceName(resourceName: string): string {
  // Ensure PascalCase without "I" prefix
  return `${resourceName[0].toUpperCase()}${resourceName.slice(1)}`;
}

/**
 * Convert underscore or dash-separated string to camelCase
 * Examples:
 *   giantswarm_application -> giantswarmApplication
 *   external-secrets -> externalSecrets
 *   crossplane_aws -> crossplaneAws
 */
export function toCamelCase(str: string): string {
  return str.replace(/[_-]([a-z])/g, (_, char) => char.toUpperCase());
}

export function formatTypesFileHeader(): string {
  return `${autoGeneratedWarningMessage}

import * as metav1 from '../../../core/meta/v1';
`;
}

export function formatFileHeader(): string {
  return `${autoGeneratedWarningMessage}
`;
}

